# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Σ∀i
tagline:          
description:      'An assortment of expositions , musings and ramblings ranging from math to intelliegnce , life and beyond '
url:              http://rsn870.github.io
baseurl:          /

author:
  name:           'Sai Niranjan'
  url:            https://github.com/rsn870

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rsn870/rsn870.github.io
